language: bash
services: docker

env:
  - SOFT=7.0 REPO=shion/php-fpm:7.0
  - SOFT=7.1 REPO=shion/php-fpm:7.1
  - SOFT=7.2 REPO=shion/php-fpm:7.2
  - SOFT=7.3 REPO=shion/php-fpm:7.3
  - SOFT=7.4 REPO=shion/php-fpm:7.4
  - SOFT=8.0 REPO=shion/php-fpm:8.0

before_script:
  - env
  - cd "$SOFT"
  - image="${REPO}"

script:
  - docker build ./ -t "$image"

after_script:
  - docker images