name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push php7.0
        uses: docker/build-push-action@v2
        with:
          context: ./7.0
          push: true
          tags: shion/php-fpm:7.0
      -
        name: Build and push php7.1
        uses: docker/build-push-action@v2
        with:
          context: ./7.1
          push: true
          tags: shion/php-fpm:7.1
      -
        name: Build and push php7.2
        uses: docker/build-push-action@v2
        with:
          context: ./7.2
          push: true
          tags: shion/php-fpm:7.2
      -
        name: Build and push php7.3
        uses: docker/build-push-action@v2
        with:
          context: ./7.3
          push: true
          tags: shion/php-fpm:7.3
      -
        name: Build and push php7.4
        uses: docker/build-push-action@v2
        with:
          context: ./7.4
          push: true
          tags: shion/php-fpm:7.4
      -
        name: Build and push php8.0
        uses: docker/build-push-action@v2
        with:
          context: ./8.0
          push: true
          tags: shion/php-fpm:8.0,shion/php-fpm:latest
