name: php-fpm 7.0

on:
  push:
    branches:
      - 'master/7.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push php7.0
        uses: docker/build-push-action@v2
        with:
          context: ./7.0
          push: true
          tags: shion/php-fpm:7.0
