name: php-fpm 8.3

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      -
        name: Build and push php8.3
        uses: docker/build-push-action@v2
        with:
          context: ./8.3
          push: true
          tags: shion/php-fpm:8.3
      -
        name: Build and push php8.3
        uses: docker/build-push-action@v2
        with:
          context: ./8.3
          push: true
          tags: shion/php-fpm:latest